services:
  - type: web
    name: kingdom-rag-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        value: us-east-1-aws
      - key: PINECONE_INDEX_NAME
        value: kingdom-design-house
      - key: HUBSPOT_ACCESS_TOKEN
        sync: false
      - key: HUBSPOT_PORTAL_ID
        sync: false